New log file opened at Mon Apr 20 18:10:50 CEST 2015 by 7240@Sebbe-Dator
Taking next connection to: 54185
New client attempting to connect on port: 54186-54185
  Address = /192.168.1.29:54185
This client on port 54186 has uuid f8e20e69-29ee-43a6-9f03-3081ef7abc29 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-f8e20e69-29ee-43a6-9f03-3081ef7abc29
Taking next connection to: 54185
New client attempting to connect on port: 54187-54185
  Address = /192.168.1.29:54185
Handshake exception on socket: 54187
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 54185
New client attempting to connect on port: 54188-54185
  Address = /192.168.1.29:54185
This client on port 54188 has uuid 82667661-558f-4cae-9404-59862aaadf62 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-f8e20e69-29ee-43a6-9f03-3081ef7abc29, activator-82667661-558f-4cae-9404-59862aaadf62
Taking next connection to: 54185
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54185
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54185
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54185
